{
    "name": """Tecfy Salla Odoo Inventory Connector""",
    "summary": """Update the quantity of products in Salla from Odoo""",
    "category": "Extra Tools",
    "images": ["https://tecfy.co/assets/images/logo.svg"],
    "version": "1.3.6",
    "application": False,
    "author": "tecfy.co",
    "support": "info@tecfy.co",
    "images": [
        "static/description/banner.png",
    ],
    "website": "https://tecfy.co",
    "license": "Other OSI approved licence",
    "depends": ["stock", "sale_management"],
    "external_dependencies": {"python": [], "bin": []},
    "data": ['views/company_view.xml', 'views/activity.xml','security/ir.model.access.csv'],
    "demo": [],
    "qweb": [],
    "post_load": None,
    "pre_init_hook": None,
    "post_init_hook": None,
    "uninstall_hook": None,
    "auto_install": False,
    "installable": True,
}
